---
name: Test

# yamllint disable-line rule:truthy
on:
  pull_request:
  push:

jobs:

  upload:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/upload-artifact@v4
        with:
          name: foo.bar
          path: "*.*"

  download:
    needs: upload
    runs-on: ubuntu-latest
    steps:
      - uses: actions/download-artifact@v4
        with:
          name: foo.bar
          path: .
